CC = g++
LIBS = -lm
SRC = src
OBJ = obj
INC = include
BIN = bin
CFLAGS = -Wall -c -I$(INC)

EXE = $(BIN)/main

run:  $(EXE)
	clear
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example01.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example02.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example03.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example04.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example05.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example06.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example07.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example08.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example09.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example10.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example11.txt
	./a.out  /home/bdlemos/Faculdade/Semestre_5/PO/TP2/instancias2/example12.txt

$(BIN)/main: $(OBJS)
	$(CC) tp2_2022043949.cpp


	
clean:
	rm -rf bin/* obj/*